CLIENT_ID = "b2681b05-9f0b-4504-b750-ec0c1b8b144d"
REDIRECT_URI = "https://uim-samhita-dev.pacewisdom.in/auth/callback"
AUTHORIZATION_ENDPOINT = "https://connectuat.csccloud.in/account/authorize"
TOKEN_ENDPOINT = "https://connectuat.csccloud.in/account/token"
RESOURCE_URL = "https://connectuat.csccloud.in/account/resource"
CLIENT_SECRET = "tgLjqz3pirYk"
CLIENT_TOKEN = "PM8A7zhDmpz8jGP9"
